apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: mysql-secrets
    type: Opaque
    data:
    - objectName: root-password
      key: root-password
    - objectName: username
      key: username
    - objectName: user-password
      key: user-password
  parameters:
    usePodIdentity: "false"  
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: "" 
    keyvaultName: "kvdinesh007"
    objects:  |
      array:
        - |
          objectName: root-password
          objectType: secret
        - |
          objectName: username
          objectType: secret
        - |
          objectName: user-password
          objectType: secret
    tenantId: "62c65783-e48b-4438-8d2a-50fb84685b6e"
